apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-backendconfig-internal
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 2
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 80
  sessionAffinity:
    affinityType: "CLIENT_IP"
  connectionDraining:
    drainingTimeoutSec: 10